spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.internal.jdbc.JdbcTransactionFactory
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
    open-in-view: off
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mst_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  mvc:
    hidden method:
      filter:
        enabled: true
server:
  port: 8080